package com.jzfq.house.mybatis.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class HouseMessageQuery {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table house_message
     *
     * @mbggenerated Mon Sep 10 10:04:36 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table house_message
     *
     * @mbggenerated Mon Sep 10 10:04:36 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table house_message
     *
     * @mbggenerated Mon Sep 10 10:04:36 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_message
     *
     * @mbggenerated Mon Sep 10 10:04:36 CST 2018
     */
    public HouseMessageQuery() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_message
     *
     * @mbggenerated Mon Sep 10 10:04:36 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_message
     *
     * @mbggenerated Mon Sep 10 10:04:36 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_message
     *
     * @mbggenerated Mon Sep 10 10:04:36 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_message
     *
     * @mbggenerated Mon Sep 10 10:04:36 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_message
     *
     * @mbggenerated Mon Sep 10 10:04:36 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_message
     *
     * @mbggenerated Mon Sep 10 10:04:36 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_message
     *
     * @mbggenerated Mon Sep 10 10:04:36 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_message
     *
     * @mbggenerated Mon Sep 10 10:04:36 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_message
     *
     * @mbggenerated Mon Sep 10 10:04:36 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_message
     *
     * @mbggenerated Mon Sep 10 10:04:36 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table house_message
     *
     * @mbggenerated Mon Sep 10 10:04:36 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("houseMessage.id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("houseMessage.id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("houseMessage.id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("houseMessage.id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("houseMessage.id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("houseMessage.id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("houseMessage.id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("houseMessage.id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("houseMessage.id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("houseMessage.id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("houseMessage.id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("houseMessage.id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andHouseIdIsNull() {
            addCriterion("houseMessage.house_id is null");
            return (Criteria) this;
        }

        public Criteria andHouseIdIsNotNull() {
            addCriterion("houseMessage.house_id is not null");
            return (Criteria) this;
        }

        public Criteria andHouseIdEqualTo(String value) {
            addCriterion("houseMessage.house_id =", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdNotEqualTo(String value) {
            addCriterion("houseMessage.house_id <>", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdGreaterThan(String value) {
            addCriterion("houseMessage.house_id >", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdGreaterThanOrEqualTo(String value) {
            addCriterion("houseMessage.house_id >=", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdLessThan(String value) {
            addCriterion("houseMessage.house_id <", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdLessThanOrEqualTo(String value) {
            addCriterion("houseMessage.house_id <=", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdLike(String value) {
            addCriterion("houseMessage.house_id like", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdNotLike(String value) {
            addCriterion("houseMessage.house_id not like", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdIn(List<String> values) {
            addCriterion("houseMessage.house_id in", values, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdNotIn(List<String> values) {
            addCriterion("houseMessage.house_id not in", values, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdBetween(String value1, String value2) {
            addCriterion("houseMessage.house_id between", value1, value2, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdNotBetween(String value1, String value2) {
            addCriterion("houseMessage.house_id not between", value1, value2, "houseId");
            return (Criteria) this;
        }

        public Criteria andFromPersonIdIsNull() {
            addCriterion("houseMessage.from_person_id is null");
            return (Criteria) this;
        }

        public Criteria andFromPersonIdIsNotNull() {
            addCriterion("houseMessage.from_person_id is not null");
            return (Criteria) this;
        }

        public Criteria andFromPersonIdEqualTo(Integer value) {
            addCriterion("houseMessage.from_person_id =", value, "fromPersonId");
            return (Criteria) this;
        }

        public Criteria andFromPersonIdNotEqualTo(Integer value) {
            addCriterion("houseMessage.from_person_id <>", value, "fromPersonId");
            return (Criteria) this;
        }

        public Criteria andFromPersonIdGreaterThan(Integer value) {
            addCriterion("houseMessage.from_person_id >", value, "fromPersonId");
            return (Criteria) this;
        }

        public Criteria andFromPersonIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("houseMessage.from_person_id >=", value, "fromPersonId");
            return (Criteria) this;
        }

        public Criteria andFromPersonIdLessThan(Integer value) {
            addCriterion("houseMessage.from_person_id <", value, "fromPersonId");
            return (Criteria) this;
        }

        public Criteria andFromPersonIdLessThanOrEqualTo(Integer value) {
            addCriterion("houseMessage.from_person_id <=", value, "fromPersonId");
            return (Criteria) this;
        }

        public Criteria andFromPersonIdIn(List<Integer> values) {
            addCriterion("houseMessage.from_person_id in", values, "fromPersonId");
            return (Criteria) this;
        }

        public Criteria andFromPersonIdNotIn(List<Integer> values) {
            addCriterion("houseMessage.from_person_id not in", values, "fromPersonId");
            return (Criteria) this;
        }

        public Criteria andFromPersonIdBetween(Integer value1, Integer value2) {
            addCriterion("houseMessage.from_person_id between", value1, value2, "fromPersonId");
            return (Criteria) this;
        }

        public Criteria andFromPersonIdNotBetween(Integer value1, Integer value2) {
            addCriterion("houseMessage.from_person_id not between", value1, value2, "fromPersonId");
            return (Criteria) this;
        }

        public Criteria andToPersonIdIsNull() {
            addCriterion("houseMessage.to_person_id is null");
            return (Criteria) this;
        }

        public Criteria andToPersonIdIsNotNull() {
            addCriterion("houseMessage.to_person_id is not null");
            return (Criteria) this;
        }

        public Criteria andToPersonIdEqualTo(Integer value) {
            addCriterion("houseMessage.to_person_id =", value, "toPersonId");
            return (Criteria) this;
        }

        public Criteria andToPersonIdNotEqualTo(Integer value) {
            addCriterion("houseMessage.to_person_id <>", value, "toPersonId");
            return (Criteria) this;
        }

        public Criteria andToPersonIdGreaterThan(Integer value) {
            addCriterion("houseMessage.to_person_id >", value, "toPersonId");
            return (Criteria) this;
        }

        public Criteria andToPersonIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("houseMessage.to_person_id >=", value, "toPersonId");
            return (Criteria) this;
        }

        public Criteria andToPersonIdLessThan(Integer value) {
            addCriterion("houseMessage.to_person_id <", value, "toPersonId");
            return (Criteria) this;
        }

        public Criteria andToPersonIdLessThanOrEqualTo(Integer value) {
            addCriterion("houseMessage.to_person_id <=", value, "toPersonId");
            return (Criteria) this;
        }

        public Criteria andToPersonIdIn(List<Integer> values) {
            addCriterion("houseMessage.to_person_id in", values, "toPersonId");
            return (Criteria) this;
        }

        public Criteria andToPersonIdNotIn(List<Integer> values) {
            addCriterion("houseMessage.to_person_id not in", values, "toPersonId");
            return (Criteria) this;
        }

        public Criteria andToPersonIdBetween(Integer value1, Integer value2) {
            addCriterion("houseMessage.to_person_id between", value1, value2, "toPersonId");
            return (Criteria) this;
        }

        public Criteria andToPersonIdNotBetween(Integer value1, Integer value2) {
            addCriterion("houseMessage.to_person_id not between", value1, value2, "toPersonId");
            return (Criteria) this;
        }

        public Criteria andContentIsNull() {
            addCriterion("houseMessage.content is null");
            return (Criteria) this;
        }

        public Criteria andContentIsNotNull() {
            addCriterion("houseMessage.content is not null");
            return (Criteria) this;
        }

        public Criteria andContentEqualTo(String value) {
            addCriterion("houseMessage.content =", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotEqualTo(String value) {
            addCriterion("houseMessage.content <>", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThan(String value) {
            addCriterion("houseMessage.content >", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThanOrEqualTo(String value) {
            addCriterion("houseMessage.content >=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThan(String value) {
            addCriterion("houseMessage.content <", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThanOrEqualTo(String value) {
            addCriterion("houseMessage.content <=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLike(String value) {
            addCriterion("houseMessage.content like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotLike(String value) {
            addCriterion("houseMessage.content not like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentIn(List<String> values) {
            addCriterion("houseMessage.content in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotIn(List<String> values) {
            addCriterion("houseMessage.content not in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentBetween(String value1, String value2) {
            addCriterion("houseMessage.content between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotBetween(String value1, String value2) {
            addCriterion("houseMessage.content not between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andTalkTimeIsNull() {
            addCriterion("houseMessage.talk_time is null");
            return (Criteria) this;
        }

        public Criteria andTalkTimeIsNotNull() {
            addCriterion("houseMessage.talk_time is not null");
            return (Criteria) this;
        }

        public Criteria andTalkTimeEqualTo(Date value) {
            addCriterion("houseMessage.talk_time =", value, "talkTime");
            return (Criteria) this;
        }

        public Criteria andTalkTimeNotEqualTo(Date value) {
            addCriterion("houseMessage.talk_time <>", value, "talkTime");
            return (Criteria) this;
        }

        public Criteria andTalkTimeGreaterThan(Date value) {
            addCriterion("houseMessage.talk_time >", value, "talkTime");
            return (Criteria) this;
        }

        public Criteria andTalkTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("houseMessage.talk_time >=", value, "talkTime");
            return (Criteria) this;
        }

        public Criteria andTalkTimeLessThan(Date value) {
            addCriterion("houseMessage.talk_time <", value, "talkTime");
            return (Criteria) this;
        }

        public Criteria andTalkTimeLessThanOrEqualTo(Date value) {
            addCriterion("houseMessage.talk_time <=", value, "talkTime");
            return (Criteria) this;
        }

        public Criteria andTalkTimeIn(List<Date> values) {
            addCriterion("houseMessage.talk_time in", values, "talkTime");
            return (Criteria) this;
        }

        public Criteria andTalkTimeNotIn(List<Date> values) {
            addCriterion("houseMessage.talk_time not in", values, "talkTime");
            return (Criteria) this;
        }

        public Criteria andTalkTimeBetween(Date value1, Date value2) {
            addCriterion("houseMessage.talk_time between", value1, value2, "talkTime");
            return (Criteria) this;
        }

        public Criteria andTalkTimeNotBetween(Date value1, Date value2) {
            addCriterion("houseMessage.talk_time not between", value1, value2, "talkTime");
            return (Criteria) this;
        }

        public Criteria andTalkBackIsNull() {
            addCriterion("houseMessage.talk_back is null");
            return (Criteria) this;
        }

        public Criteria andTalkBackIsNotNull() {
            addCriterion("houseMessage.talk_back is not null");
            return (Criteria) this;
        }

        public Criteria andTalkBackEqualTo(String value) {
            addCriterion("houseMessage.talk_back =", value, "talkBack");
            return (Criteria) this;
        }

        public Criteria andTalkBackNotEqualTo(String value) {
            addCriterion("houseMessage.talk_back <>", value, "talkBack");
            return (Criteria) this;
        }

        public Criteria andTalkBackGreaterThan(String value) {
            addCriterion("houseMessage.talk_back >", value, "talkBack");
            return (Criteria) this;
        }

        public Criteria andTalkBackGreaterThanOrEqualTo(String value) {
            addCriterion("houseMessage.talk_back >=", value, "talkBack");
            return (Criteria) this;
        }

        public Criteria andTalkBackLessThan(String value) {
            addCriterion("houseMessage.talk_back <", value, "talkBack");
            return (Criteria) this;
        }

        public Criteria andTalkBackLessThanOrEqualTo(String value) {
            addCriterion("houseMessage.talk_back <=", value, "talkBack");
            return (Criteria) this;
        }

        public Criteria andTalkBackLike(String value) {
            addCriterion("houseMessage.talk_back like", value, "talkBack");
            return (Criteria) this;
        }

        public Criteria andTalkBackNotLike(String value) {
            addCriterion("houseMessage.talk_back not like", value, "talkBack");
            return (Criteria) this;
        }

        public Criteria andTalkBackIn(List<String> values) {
            addCriterion("houseMessage.talk_back in", values, "talkBack");
            return (Criteria) this;
        }

        public Criteria andTalkBackNotIn(List<String> values) {
            addCriterion("houseMessage.talk_back not in", values, "talkBack");
            return (Criteria) this;
        }

        public Criteria andTalkBackBetween(String value1, String value2) {
            addCriterion("houseMessage.talk_back between", value1, value2, "talkBack");
            return (Criteria) this;
        }

        public Criteria andTalkBackNotBetween(String value1, String value2) {
            addCriterion("houseMessage.talk_back not between", value1, value2, "talkBack");
            return (Criteria) this;
        }

        public Criteria andBackTimeIsNull() {
            addCriterion("houseMessage.back_time is null");
            return (Criteria) this;
        }

        public Criteria andBackTimeIsNotNull() {
            addCriterion("houseMessage.back_time is not null");
            return (Criteria) this;
        }

        public Criteria andBackTimeEqualTo(Date value) {
            addCriterion("houseMessage.back_time =", value, "backTime");
            return (Criteria) this;
        }

        public Criteria andBackTimeNotEqualTo(Date value) {
            addCriterion("houseMessage.back_time <>", value, "backTime");
            return (Criteria) this;
        }

        public Criteria andBackTimeGreaterThan(Date value) {
            addCriterion("houseMessage.back_time >", value, "backTime");
            return (Criteria) this;
        }

        public Criteria andBackTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("houseMessage.back_time >=", value, "backTime");
            return (Criteria) this;
        }

        public Criteria andBackTimeLessThan(Date value) {
            addCriterion("houseMessage.back_time <", value, "backTime");
            return (Criteria) this;
        }

        public Criteria andBackTimeLessThanOrEqualTo(Date value) {
            addCriterion("houseMessage.back_time <=", value, "backTime");
            return (Criteria) this;
        }

        public Criteria andBackTimeIn(List<Date> values) {
            addCriterion("houseMessage.back_time in", values, "backTime");
            return (Criteria) this;
        }

        public Criteria andBackTimeNotIn(List<Date> values) {
            addCriterion("houseMessage.back_time not in", values, "backTime");
            return (Criteria) this;
        }

        public Criteria andBackTimeBetween(Date value1, Date value2) {
            addCriterion("houseMessage.back_time between", value1, value2, "backTime");
            return (Criteria) this;
        }

        public Criteria andBackTimeNotBetween(Date value1, Date value2) {
            addCriterion("houseMessage.back_time not between", value1, value2, "backTime");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("houseMessage.description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("houseMessage.description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("houseMessage.description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("houseMessage.description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("houseMessage.description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("houseMessage.description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("houseMessage.description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("houseMessage.description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("houseMessage.description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("houseMessage.description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("houseMessage.description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("houseMessage.description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("houseMessage.description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("houseMessage.description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDelIsNull() {
            addCriterion("houseMessage.del is null");
            return (Criteria) this;
        }

        public Criteria andDelIsNotNull() {
            addCriterion("houseMessage.del is not null");
            return (Criteria) this;
        }

        public Criteria andDelEqualTo(Integer value) {
            addCriterion("houseMessage.del =", value, "del");
            return (Criteria) this;
        }

        public Criteria andDelNotEqualTo(Integer value) {
            addCriterion("houseMessage.del <>", value, "del");
            return (Criteria) this;
        }

        public Criteria andDelGreaterThan(Integer value) {
            addCriterion("houseMessage.del >", value, "del");
            return (Criteria) this;
        }

        public Criteria andDelGreaterThanOrEqualTo(Integer value) {
            addCriterion("houseMessage.del >=", value, "del");
            return (Criteria) this;
        }

        public Criteria andDelLessThan(Integer value) {
            addCriterion("houseMessage.del <", value, "del");
            return (Criteria) this;
        }

        public Criteria andDelLessThanOrEqualTo(Integer value) {
            addCriterion("houseMessage.del <=", value, "del");
            return (Criteria) this;
        }

        public Criteria andDelIn(List<Integer> values) {
            addCriterion("houseMessage.del in", values, "del");
            return (Criteria) this;
        }

        public Criteria andDelNotIn(List<Integer> values) {
            addCriterion("houseMessage.del not in", values, "del");
            return (Criteria) this;
        }

        public Criteria andDelBetween(Integer value1, Integer value2) {
            addCriterion("houseMessage.del between", value1, value2, "del");
            return (Criteria) this;
        }

        public Criteria andDelNotBetween(Integer value1, Integer value2) {
            addCriterion("houseMessage.del not between", value1, value2, "del");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("houseMessage.create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("houseMessage.create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("houseMessage.create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("houseMessage.create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("houseMessage.create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("houseMessage.create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("houseMessage.create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("houseMessage.create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("houseMessage.create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("houseMessage.create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("houseMessage.create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("houseMessage.create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("houseMessage.create_user is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("houseMessage.create_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("houseMessage.create_user =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("houseMessage.create_user <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("houseMessage.create_user >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("houseMessage.create_user >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("houseMessage.create_user <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("houseMessage.create_user <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("houseMessage.create_user like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("houseMessage.create_user not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("houseMessage.create_user in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("houseMessage.create_user not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("houseMessage.create_user between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("houseMessage.create_user not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("houseMessage.update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("houseMessage.update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("houseMessage.update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("houseMessage.update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("houseMessage.update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("houseMessage.update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("houseMessage.update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("houseMessage.update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("houseMessage.update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("houseMessage.update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("houseMessage.update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("houseMessage.update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNull() {
            addCriterion("houseMessage.update_user is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNotNull() {
            addCriterion("houseMessage.update_user is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualTo(String value) {
            addCriterion("houseMessage.update_user =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualTo(String value) {
            addCriterion("houseMessage.update_user <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThan(String value) {
            addCriterion("houseMessage.update_user >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
            addCriterion("houseMessage.update_user >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThan(String value) {
            addCriterion("houseMessage.update_user <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualTo(String value) {
            addCriterion("houseMessage.update_user <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLike(String value) {
            addCriterion("houseMessage.update_user like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotLike(String value) {
            addCriterion("houseMessage.update_user not like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIn(List<String> values) {
            addCriterion("houseMessage.update_user in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotIn(List<String> values) {
            addCriterion("houseMessage.update_user not in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserBetween(String value1, String value2) {
            addCriterion("houseMessage.update_user between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotBetween(String value1, String value2) {
            addCriterion("houseMessage.update_user not between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andHouseIdLikeInsensitive(String value) {
            addCriterion("upper(houseMessage.house_id) like", value.toUpperCase(), "houseId");
            return (Criteria) this;
        }

        public Criteria andContentLikeInsensitive(String value) {
            addCriterion("upper(houseMessage.content) like", value.toUpperCase(), "content");
            return (Criteria) this;
        }

        public Criteria andTalkBackLikeInsensitive(String value) {
            addCriterion("upper(houseMessage.talk_back) like", value.toUpperCase(), "talkBack");
            return (Criteria) this;
        }

        public Criteria andDescriptionLikeInsensitive(String value) {
            addCriterion("upper(houseMessage.description) like", value.toUpperCase(), "description");
            return (Criteria) this;
        }

        public Criteria andCreateUserLikeInsensitive(String value) {
            addCriterion("upper(houseMessage.create_user) like", value.toUpperCase(), "createUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLikeInsensitive(String value) {
            addCriterion("upper(houseMessage.update_user) like", value.toUpperCase(), "updateUser");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table house_message
     *
     * @mbggenerated do_not_delete_during_merge Mon Sep 10 10:04:36 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table house_message
     *
     * @mbggenerated Mon Sep 10 10:04:36 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}