package com.jzfq.house.mybatis.domain;

import java.io.Serializable;
import java.util.Date;

public class Person implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.id
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.name
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.classify
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    private Integer classify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.type
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.org_id
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    private Integer orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.mobile1
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    private String mobile1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.mobile2
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    private String mobile2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.add_time
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.add_person
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    private String addPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.status
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.username
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.password
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.shield_state
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    private Integer shieldState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.remark
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.del
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    private Integer del;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.create_time
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.create_user
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.update_time
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.update_user
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table person
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.id
     *
     * @return the value of person.id
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.id
     *
     * @param id the value for person.id
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.name
     *
     * @return the value of person.name
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.name
     *
     * @param name the value for person.name
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.classify
     *
     * @return the value of person.classify
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    public Integer getClassify() {
        return classify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.classify
     *
     * @param classify the value for person.classify
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    public void setClassify(Integer classify) {
        this.classify = classify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.type
     *
     * @return the value of person.type
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.type
     *
     * @param type the value for person.type
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.org_id
     *
     * @return the value of person.org_id
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    public Integer getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.org_id
     *
     * @param orgId the value for person.org_id
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.mobile1
     *
     * @return the value of person.mobile1
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    public String getMobile1() {
        return mobile1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.mobile1
     *
     * @param mobile1 the value for person.mobile1
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    public void setMobile1(String mobile1) {
        this.mobile1 = mobile1 == null ? null : mobile1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.mobile2
     *
     * @return the value of person.mobile2
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    public String getMobile2() {
        return mobile2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.mobile2
     *
     * @param mobile2 the value for person.mobile2
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    public void setMobile2(String mobile2) {
        this.mobile2 = mobile2 == null ? null : mobile2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.add_time
     *
     * @return the value of person.add_time
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.add_time
     *
     * @param addTime the value for person.add_time
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.add_person
     *
     * @return the value of person.add_person
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    public String getAddPerson() {
        return addPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.add_person
     *
     * @param addPerson the value for person.add_person
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    public void setAddPerson(String addPerson) {
        this.addPerson = addPerson == null ? null : addPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.status
     *
     * @return the value of person.status
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.status
     *
     * @param status the value for person.status
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.username
     *
     * @return the value of person.username
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.username
     *
     * @param username the value for person.username
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.password
     *
     * @return the value of person.password
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.password
     *
     * @param password the value for person.password
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.shield_state
     *
     * @return the value of person.shield_state
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    public Integer getShieldState() {
        return shieldState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.shield_state
     *
     * @param shieldState the value for person.shield_state
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    public void setShieldState(Integer shieldState) {
        this.shieldState = shieldState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.remark
     *
     * @return the value of person.remark
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.remark
     *
     * @param remark the value for person.remark
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.del
     *
     * @return the value of person.del
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    public Integer getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.del
     *
     * @param del the value for person.del
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    public void setDel(Integer del) {
        this.del = del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.create_time
     *
     * @return the value of person.create_time
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.create_time
     *
     * @param createTime the value for person.create_time
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.create_user
     *
     * @return the value of person.create_user
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.create_user
     *
     * @param createUser the value for person.create_user
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.update_time
     *
     * @return the value of person.update_time
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.update_time
     *
     * @param updateTime the value for person.update_time
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.update_user
     *
     * @return the value of person.update_user
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.update_user
     *
     * @param updateUser the value for person.update_user
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Person other = (Person) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getClassify() == null ? other.getClassify() == null : this.getClassify().equals(other.getClassify()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getOrgId() == null ? other.getOrgId() == null : this.getOrgId().equals(other.getOrgId()))
            && (this.getMobile1() == null ? other.getMobile1() == null : this.getMobile1().equals(other.getMobile1()))
            && (this.getMobile2() == null ? other.getMobile2() == null : this.getMobile2().equals(other.getMobile2()))
            && (this.getAddTime() == null ? other.getAddTime() == null : this.getAddTime().equals(other.getAddTime()))
            && (this.getAddPerson() == null ? other.getAddPerson() == null : this.getAddPerson().equals(other.getAddPerson()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getUsername() == null ? other.getUsername() == null : this.getUsername().equals(other.getUsername()))
            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
            && (this.getShieldState() == null ? other.getShieldState() == null : this.getShieldState().equals(other.getShieldState()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.getDel() == null ? other.getDel() == null : this.getDel().equals(other.getDel()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getUpdateUser() == null ? other.getUpdateUser() == null : this.getUpdateUser().equals(other.getUpdateUser()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getClassify() == null) ? 0 : getClassify().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getOrgId() == null) ? 0 : getOrgId().hashCode());
        result = prime * result + ((getMobile1() == null) ? 0 : getMobile1().hashCode());
        result = prime * result + ((getMobile2() == null) ? 0 : getMobile2().hashCode());
        result = prime * result + ((getAddTime() == null) ? 0 : getAddTime().hashCode());
        result = prime * result + ((getAddPerson() == null) ? 0 : getAddPerson().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getShieldState() == null) ? 0 : getShieldState().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getDel() == null) ? 0 : getDel().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getUpdateUser() == null) ? 0 : getUpdateUser().hashCode());
        return result;
    }
}