package com.jzfq.house.mybatis.domain;

import java.io.Serializable;
import java.util.Date;

public class ResRecordFile implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_record_file.id
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_record_file.project_link_id
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    private Integer projectLinkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_record_file.resources_record_id
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    private Integer resourcesRecordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_record_file.person_id
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    private Integer personId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_record_file.person_name
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    private String personName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_record_file.type
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_record_file.url
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_record_file.remark
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_record_file.del
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    private Integer del;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_record_file.create_time
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_record_file.create_user
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_record_file.update_time
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_record_file.update_user
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table res_record_file
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_record_file.id
     *
     * @return the value of res_record_file.id
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_record_file.id
     *
     * @param id the value for res_record_file.id
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_record_file.project_link_id
     *
     * @return the value of res_record_file.project_link_id
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    public Integer getProjectLinkId() {
        return projectLinkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_record_file.project_link_id
     *
     * @param projectLinkId the value for res_record_file.project_link_id
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    public void setProjectLinkId(Integer projectLinkId) {
        this.projectLinkId = projectLinkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_record_file.resources_record_id
     *
     * @return the value of res_record_file.resources_record_id
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    public Integer getResourcesRecordId() {
        return resourcesRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_record_file.resources_record_id
     *
     * @param resourcesRecordId the value for res_record_file.resources_record_id
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    public void setResourcesRecordId(Integer resourcesRecordId) {
        this.resourcesRecordId = resourcesRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_record_file.person_id
     *
     * @return the value of res_record_file.person_id
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    public Integer getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_record_file.person_id
     *
     * @param personId the value for res_record_file.person_id
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    public void setPersonId(Integer personId) {
        this.personId = personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_record_file.person_name
     *
     * @return the value of res_record_file.person_name
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    public String getPersonName() {
        return personName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_record_file.person_name
     *
     * @param personName the value for res_record_file.person_name
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    public void setPersonName(String personName) {
        this.personName = personName == null ? null : personName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_record_file.type
     *
     * @return the value of res_record_file.type
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_record_file.type
     *
     * @param type the value for res_record_file.type
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_record_file.url
     *
     * @return the value of res_record_file.url
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_record_file.url
     *
     * @param url the value for res_record_file.url
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_record_file.remark
     *
     * @return the value of res_record_file.remark
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_record_file.remark
     *
     * @param remark the value for res_record_file.remark
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_record_file.del
     *
     * @return the value of res_record_file.del
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    public Integer getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_record_file.del
     *
     * @param del the value for res_record_file.del
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    public void setDel(Integer del) {
        this.del = del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_record_file.create_time
     *
     * @return the value of res_record_file.create_time
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_record_file.create_time
     *
     * @param createTime the value for res_record_file.create_time
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_record_file.create_user
     *
     * @return the value of res_record_file.create_user
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_record_file.create_user
     *
     * @param createUser the value for res_record_file.create_user
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_record_file.update_time
     *
     * @return the value of res_record_file.update_time
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_record_file.update_time
     *
     * @param updateTime the value for res_record_file.update_time
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_record_file.update_user
     *
     * @return the value of res_record_file.update_user
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_record_file.update_user
     *
     * @param updateUser the value for res_record_file.update_user
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_record_file
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ResRecordFile other = (ResRecordFile) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getProjectLinkId() == null ? other.getProjectLinkId() == null : this.getProjectLinkId().equals(other.getProjectLinkId()))
            && (this.getResourcesRecordId() == null ? other.getResourcesRecordId() == null : this.getResourcesRecordId().equals(other.getResourcesRecordId()))
            && (this.getPersonId() == null ? other.getPersonId() == null : this.getPersonId().equals(other.getPersonId()))
            && (this.getPersonName() == null ? other.getPersonName() == null : this.getPersonName().equals(other.getPersonName()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getUrl() == null ? other.getUrl() == null : this.getUrl().equals(other.getUrl()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.getDel() == null ? other.getDel() == null : this.getDel().equals(other.getDel()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getUpdateUser() == null ? other.getUpdateUser() == null : this.getUpdateUser().equals(other.getUpdateUser()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_record_file
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getProjectLinkId() == null) ? 0 : getProjectLinkId().hashCode());
        result = prime * result + ((getResourcesRecordId() == null) ? 0 : getResourcesRecordId().hashCode());
        result = prime * result + ((getPersonId() == null) ? 0 : getPersonId().hashCode());
        result = prime * result + ((getPersonName() == null) ? 0 : getPersonName().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getUrl() == null) ? 0 : getUrl().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getDel() == null) ? 0 : getDel().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getUpdateUser() == null) ? 0 : getUpdateUser().hashCode());
        return result;
    }
}