package com.jzfq.house.mybatis.domain;

import java.io.Serializable;
import java.util.Date;

public class TemplateLink implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template_link.id
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template_link.template_id
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    private Integer templateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template_link.template_name
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    private String templateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template_link.link_id
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    private Integer linkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template_link.link_name
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    private String linkName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template_link.del
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    private Integer del;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template_link.create_time
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template_link.create_user
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template_link.update_time
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template_link.update_user
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table template_link
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template_link.id
     *
     * @return the value of template_link.id
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template_link.id
     *
     * @param id the value for template_link.id
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template_link.template_id
     *
     * @return the value of template_link.template_id
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    public Integer getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template_link.template_id
     *
     * @param templateId the value for template_link.template_id
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    public void setTemplateId(Integer templateId) {
        this.templateId = templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template_link.template_name
     *
     * @return the value of template_link.template_name
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    public String getTemplateName() {
        return templateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template_link.template_name
     *
     * @param templateName the value for template_link.template_name
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    public void setTemplateName(String templateName) {
        this.templateName = templateName == null ? null : templateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template_link.link_id
     *
     * @return the value of template_link.link_id
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    public Integer getLinkId() {
        return linkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template_link.link_id
     *
     * @param linkId the value for template_link.link_id
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    public void setLinkId(Integer linkId) {
        this.linkId = linkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template_link.link_name
     *
     * @return the value of template_link.link_name
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    public String getLinkName() {
        return linkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template_link.link_name
     *
     * @param linkName the value for template_link.link_name
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    public void setLinkName(String linkName) {
        this.linkName = linkName == null ? null : linkName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template_link.del
     *
     * @return the value of template_link.del
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    public Integer getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template_link.del
     *
     * @param del the value for template_link.del
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    public void setDel(Integer del) {
        this.del = del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template_link.create_time
     *
     * @return the value of template_link.create_time
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template_link.create_time
     *
     * @param createTime the value for template_link.create_time
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template_link.create_user
     *
     * @return the value of template_link.create_user
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template_link.create_user
     *
     * @param createUser the value for template_link.create_user
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template_link.update_time
     *
     * @return the value of template_link.update_time
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template_link.update_time
     *
     * @param updateTime the value for template_link.update_time
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template_link.update_user
     *
     * @return the value of template_link.update_user
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template_link.update_user
     *
     * @param updateUser the value for template_link.update_user
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_link
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TemplateLink other = (TemplateLink) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getTemplateId() == null ? other.getTemplateId() == null : this.getTemplateId().equals(other.getTemplateId()))
            && (this.getTemplateName() == null ? other.getTemplateName() == null : this.getTemplateName().equals(other.getTemplateName()))
            && (this.getLinkId() == null ? other.getLinkId() == null : this.getLinkId().equals(other.getLinkId()))
            && (this.getLinkName() == null ? other.getLinkName() == null : this.getLinkName().equals(other.getLinkName()))
            && (this.getDel() == null ? other.getDel() == null : this.getDel().equals(other.getDel()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getUpdateUser() == null ? other.getUpdateUser() == null : this.getUpdateUser().equals(other.getUpdateUser()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_link
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTemplateId() == null) ? 0 : getTemplateId().hashCode());
        result = prime * result + ((getTemplateName() == null) ? 0 : getTemplateName().hashCode());
        result = prime * result + ((getLinkId() == null) ? 0 : getLinkId().hashCode());
        result = prime * result + ((getLinkName() == null) ? 0 : getLinkName().hashCode());
        result = prime * result + ((getDel() == null) ? 0 : getDel().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getUpdateUser() == null) ? 0 : getUpdateUser().hashCode());
        return result;
    }
}