package com.jzfq.house.mybatis.mapper;

import com.jzfq.house.mybatis.domain.HouseRecord;
import com.jzfq.house.mybatis.domain.HouseRecordQuery;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface HouseRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_record
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    int countByExample(HouseRecordQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_record
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    int deleteByExample(HouseRecordQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_record
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_record
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    int insert(HouseRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_record
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    int insertSelective(HouseRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_record
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    List<HouseRecord> selectByExample(HouseRecordQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_record
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    HouseRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_record
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    int updateByExampleSelective(@Param("record") HouseRecord record, @Param("example") HouseRecordQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_record
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    int updateByExample(@Param("record") HouseRecord record, @Param("example") HouseRecordQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_record
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    int updateByPrimaryKeySelective(HouseRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_record
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    int updateByPrimaryKey(HouseRecord record);
}