package com.jzfq.house.mybatis.mapper;

import com.jzfq.house.mybatis.domain.LinkPerson;
import com.jzfq.house.mybatis.domain.LinkPersonQuery;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LinkPersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_person
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    int countByExample(LinkPersonQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_person
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    int deleteByExample(LinkPersonQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_person
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_person
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    int insert(LinkPerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_person
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    int insertSelective(LinkPerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_person
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    List<LinkPerson> selectByExample(LinkPersonQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_person
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    LinkPerson selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_person
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    int updateByExampleSelective(@Param("record") LinkPerson record, @Param("example") LinkPersonQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_person
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    int updateByExample(@Param("record") LinkPerson record, @Param("example") LinkPersonQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_person
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    int updateByPrimaryKeySelective(LinkPerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_person
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    int updateByPrimaryKey(LinkPerson record);
}