package com.jzfq.house.mybatis.mapper;

import com.jzfq.house.mybatis.domain.Person;
import com.jzfq.house.mybatis.domain.PersonQuery;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    int countByExample(PersonQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    int deleteByExample(PersonQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    int insert(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    int insertSelective(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    List<Person> selectByExample(PersonQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    Person selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    int updateByExampleSelective(@Param("record") Person record, @Param("example") PersonQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    int updateByExample(@Param("record") Person record, @Param("example") PersonQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    int updateByPrimaryKeySelective(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Thu Sep 06 14:26:49 CST 2018
     */
    int updateByPrimaryKey(Person record);
}