package com.jzfq.house.mybatis.mapper;

import com.jzfq.house.mybatis.domain.ProjectLink;
import com.jzfq.house.mybatis.domain.ProjectLinkQuery;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ProjectLinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_link
     *
     * @mbggenerated Wed Sep 05 16:14:56 CST 2018
     */
    int countByExample(ProjectLinkQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_link
     *
     * @mbggenerated Wed Sep 05 16:14:56 CST 2018
     */
    int deleteByExample(ProjectLinkQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_link
     *
     * @mbggenerated Wed Sep 05 16:14:56 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_link
     *
     * @mbggenerated Wed Sep 05 16:14:56 CST 2018
     */
    int insert(ProjectLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_link
     *
     * @mbggenerated Wed Sep 05 16:14:56 CST 2018
     */
    int insertSelective(ProjectLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_link
     *
     * @mbggenerated Wed Sep 05 16:14:56 CST 2018
     */
    List<ProjectLink> selectByExample(ProjectLinkQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_link
     *
     * @mbggenerated Wed Sep 05 16:14:56 CST 2018
     */
    ProjectLink selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_link
     *
     * @mbggenerated Wed Sep 05 16:14:56 CST 2018
     */
    int updateByExampleSelective(@Param("record") ProjectLink record, @Param("example") ProjectLinkQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_link
     *
     * @mbggenerated Wed Sep 05 16:14:56 CST 2018
     */
    int updateByExample(@Param("record") ProjectLink record, @Param("example") ProjectLinkQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_link
     *
     * @mbggenerated Wed Sep 05 16:14:56 CST 2018
     */
    int updateByPrimaryKeySelective(ProjectLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_link
     *
     * @mbggenerated Wed Sep 05 16:14:56 CST 2018
     */
    int updateByPrimaryKey(ProjectLink record);
}