package com.jzfq.house.mybatis.mapper;

import com.jzfq.house.mybatis.domain.ResourcesRecord;
import com.jzfq.house.mybatis.domain.ResourcesRecordQuery;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ResourcesRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources_record
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    int countByExample(ResourcesRecordQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources_record
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    int deleteByExample(ResourcesRecordQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources_record
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources_record
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    int insert(ResourcesRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources_record
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    int insertSelective(ResourcesRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources_record
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    List<ResourcesRecord> selectByExample(ResourcesRecordQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources_record
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    ResourcesRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources_record
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    int updateByExampleSelective(@Param("record") ResourcesRecord record, @Param("example") ResourcesRecordQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources_record
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    int updateByExample(@Param("record") ResourcesRecord record, @Param("example") ResourcesRecordQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources_record
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    int updateByPrimaryKeySelective(ResourcesRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources_record
     *
     * @mbggenerated Mon Sep 03 15:18:29 CST 2018
     */
    int updateByPrimaryKey(ResourcesRecord record);
}