package com.jzfq.house.mybatis.mapper;

import com.jzfq.house.mybatis.domain.SysUser;
import com.jzfq.house.mybatis.domain.SysUserQuery;
import org.apache.ibatis.annotations.Param;

import java.io.Serializable;
import java.util.List;

public interface SysUserMapper <T,Q,PK extends Serializable> extends CommonMapper<T, Q,PK> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Wed Apr 18 17:07:26 CST 2018
     */
    int countByExample(SysUserQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Wed Apr 18 17:07:26 CST 2018
     */
    int deleteByExample(SysUserQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Wed Apr 18 17:07:26 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Wed Apr 18 17:07:26 CST 2018
     */
    int insert(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Wed Apr 18 17:07:26 CST 2018
     */
    int insertSelective(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Wed Apr 18 17:07:26 CST 2018
     */
    List<SysUser> selectByExample(SysUserQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Wed Apr 18 17:07:26 CST 2018
     */
    SysUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Wed Apr 18 17:07:26 CST 2018
     */
    int updateByExampleSelective(@Param("record") SysUser record, @Param("example") SysUserQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Wed Apr 18 17:07:26 CST 2018
     */
    int updateByExample(@Param("record") SysUser record, @Param("example") SysUserQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Wed Apr 18 17:07:26 CST 2018
     */
    int updateByPrimaryKeySelective(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Wed Apr 18 17:07:26 CST 2018
     */
    int updateByPrimaryKey(SysUser record);
}